elasticsearch:
  image: elasticsearch:2.2
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - /tmp/data:/usr/share/elasticsearch/data
    - /tmp/log:/var/log/elasticsearch
  restart: always
logstash:
  image: logstash:2.2
  command: logstash -f /etc/logstash/conf.d
  volumes:
    - ./logstash/conf.d/01-lumberjack-input.conf:/etc/logstash/conf.d/01-lumberjack-input.conf
    - ./logstash/conf.d/02-beats-input.conf:/etc/logstash/conf.d/02-beats-input.conf
    - ./logstash/conf.d/10-syslog.conf:/etc/logstash/conf.d/10-syslog.conf
    - ./logstash/conf.d/11-nginx.conf:/etc/logstash/conf.d/11-nginx.conf
    - ./logstash/conf.d/30-output.conf:/etc/logstash/conf.d/30-output.conf
    - ./patterns/nginx/nginx.pattern:/opt/logstash/patterns/nginx
    - ./logstash/certs:/etc/pki/tls/certs
  ports:
    - "5000:5000"
    - "5044:5044"
  links:
    - elasticsearch
  restart: always
kibana:
  image: kibana:4.4
  ports:
    - "5601:5601"
  links:
    - elasticsearch
  environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200
  restart: always

