elasticsearch:
  image: elasticsearch:2.2
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/elasticsearch.yml
    - /tmp/elasticsearch/data:/usr/share/elasticsearch/data
    - /tmp/elasticsearch/logs:/usr/share/elasticsearch/logs
  restart: always
logstash:
  image: logstash:2.2
  command: logstash -f /etc/logstash/conf.d
  volumes:
    - ./logstash/conf.d/02-beats-input.conf:/etc/logstash/conf.d/02-beats-input.conf
    - ./logstash/conf.d/12-json.conf:/etc/logstash/conf.d/12-json.conf
    - ./logstash/conf.d/30-output.conf:/etc/logstash/conf.d/30-output.conf
    - ./logstash/certs:/etc/pki/tls/certs
  ports:
    - "5000:5000"
    - "5044:5044"
  links:
    - elasticsearch
  restart: always
kibana:
  image: kibana:4.4
  ports:
    - "5601:5601"
  links:
    - elasticsearch
  environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200
  restart: always
