# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network :forwarded_port, host: 5088, guest: 5088
  config.vm.network :forwarded_port, host: 8088, guest: 8088
  config.vm.network :forwarded_port, host: 514, guest: 514
  config.vm.network :forwarded_port, host: 5043, guest: 5043
  config.vm.network :forwarded_port, host: 9292, guest: 9292
  config.vm.network :forwarded_port, host: 5601, guest: 5601

  config.vm.provider "virtualbox" do |v|
	  v.memory = 4096
	  v.cpus = 2
	end
end
